server:
  port: 8081
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances
          uri: https://github.com/Gerardo-Martinez-Acosta/microservices-user-bike-car
          search-paths: config-data
  application:
    name: config-service        
